name: cleanliness_campus_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  auto_route: ^9.2.2
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.2
  launcher_name: ^1.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/washer_logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/washer_logo.png"
  min_sdk_android: 21

launcher_name:
  default: "Чистота в кампусе"
