// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxpv1I4C18O5OHlwuUTc1movYMCcM2y_Y',
    appId: '1:854233612502:web:c270d487298db787728977',
    messagingSenderId: '854233612502',
    projectId: 'cleanlinesscampusapp-c7934',
    authDomain: 'cleanlinesscampusapp-c7934.firebaseapp.com',
    storageBucket: 'cleanlinesscampusapp-c7934.firebasestorage.app',
    measurementId: 'G-QDYW51BJ4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDaCu7HZ7jxiYC7qUZuAA6aJjE2bZrOOg',
    appId: '1:854233612502:android:e0a756e10857070c728977',
    messagingSenderId: '854233612502',
    projectId: 'cleanlinesscampusapp-c7934',
    storageBucket: 'cleanlinesscampusapp-c7934.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCxx0zO-bkX6xMGITILxnUxZ40Fkh5niI',
    appId: '1:854233612502:ios:ea7726cb3f917224728977',
    messagingSenderId: '854233612502',
    projectId: 'cleanlinesscampusapp-c7934',
    storageBucket: 'cleanlinesscampusapp-c7934.firebasestorage.app',
    iosBundleId: 'com.example.cleanlinessCampusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCxx0zO-bkX6xMGITILxnUxZ40Fkh5niI',
    appId: '1:854233612502:ios:ea7726cb3f917224728977',
    messagingSenderId: '854233612502',
    projectId: 'cleanlinesscampusapp-c7934',
    storageBucket: 'cleanlinesscampusapp-c7934.firebasestorage.app',
    iosBundleId: 'com.example.cleanlinessCampusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxpv1I4C18O5OHlwuUTc1movYMCcM2y_Y',
    appId: '1:854233612502:web:08eb21145e1dc99b728977',
    messagingSenderId: '854233612502',
    projectId: 'cleanlinesscampusapp-c7934',
    authDomain: 'cleanlinesscampusapp-c7934.firebaseapp.com',
    storageBucket: 'cleanlinesscampusapp-c7934.firebasestorage.app',
    measurementId: 'G-HLX6D7VWBV',
  );
}
