// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6H_bOB6vykbKtHRPLdKeYo41zlPNSHQQ',
    appId: '1:306013145528:web:6faa770805c9244155674d',
    messagingSenderId: '306013145528',
    projectId: 'cleanlinesscampusapp-8709a',
    authDomain: 'cleanlinesscampusapp-8709a.firebaseapp.com',
    storageBucket: 'cleanlinesscampusapp-8709a.firebasestorage.app',
    measurementId: 'G-CWE9MTD21D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv30heXPAexMnfNs3YXhopn54WzuVXS3c',
    appId: '1:306013145528:android:25cf285e2b0a060b55674d',
    messagingSenderId: '306013145528',
    projectId: 'cleanlinesscampusapp-8709a',
    storageBucket: 'cleanlinesscampusapp-8709a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByMnxeUVol7-7GwwOtpPLqx809EhmMkFI',
    appId: '1:306013145528:ios:177f8a1e5a95e30f55674d',
    messagingSenderId: '306013145528',
    projectId: 'cleanlinesscampusapp-8709a',
    storageBucket: 'cleanlinesscampusapp-8709a.firebasestorage.app',
    iosBundleId: 'com.example.cleanlinessCampusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByMnxeUVol7-7GwwOtpPLqx809EhmMkFI',
    appId: '1:306013145528:ios:177f8a1e5a95e30f55674d',
    messagingSenderId: '306013145528',
    projectId: 'cleanlinesscampusapp-8709a',
    storageBucket: 'cleanlinesscampusapp-8709a.firebasestorage.app',
    iosBundleId: 'com.example.cleanlinessCampusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6H_bOB6vykbKtHRPLdKeYo41zlPNSHQQ',
    appId: '1:306013145528:web:c66c25f37d1ccfaa55674d',
    messagingSenderId: '306013145528',
    projectId: 'cleanlinesscampusapp-8709a',
    authDomain: 'cleanlinesscampusapp-8709a.firebaseapp.com',
    storageBucket: 'cleanlinesscampusapp-8709a.firebasestorage.app',
    measurementId: 'G-7KB735SYS4',
  );

}